### ISSUE TITLE
SQLSTATE[HY000] [2002] Error

### ISSUE THREAD

**Issue by mrbobcaper** [shpasser/GaeSupport#4]
My Laravel project runs fine from web server. One GAE, I get my login screen which accepts my username & password. Then I get this Laravel error:

SQLSTATE[HY000] [2002] Unable to find the socket transport "unix" - did you forget to enable it when you configured PHP?

	public function createConnection($dsn, array $config, array $options)
	{
		$username = array_get($config, 'username');
 
		$password = array_get($config, 'password');
 
		return new PDO($dsn, $username, $password, $options);
	}

Any advice would be appreciated.

**Comment by shpasser** [comment]
Currently the package does not support database access. Anyway, if you could send me your stack trace I would look into it and try to add the missing pieces.

**Comment by shpasser** [comment]
Hello mrbobcaper,

If you are willing to help me with stack traces as I mentioned and explain your workflow I could try to add support for MySql to the package.

Please respond,

Best,

Ron.

**Comment by mattbucci** [comment]
I've enabled mysql for GAE  by modding my database config 

  $mysql_array = array(
        'driver'    => 'mysql',
        'unix_socket' => getenv('PRODUCTION_CLOUD_SQL_INSTANCE'),
        'host'      => '',
        'database'  => getenv('PRODUCTION_DB_NAME'),
        'username'  => getenv('PRODUCTION_DB_USERNAME'),
        'password'  => getenv('PRODUCTION_DB_PASSWORD'),
        'charset'   => 'utf8',
        'collation' => 'utf8_unicode_ci',
        'prefix'    => '',
    );

I set the variables in my app.yaml file....hopefully that helps integration and the original poster
